global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'waste2product-monitor'
    env: 'production'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          service: 'grafana'

  # PHP Application (if you add metrics endpoint)
  - job_name: 'php_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:9000']
        labels:
          service: 'waste2product-app'

  # MySQL Exporter (optional - requires mysqld_exporter)
  # Uncomment and add mysqld_exporter to docker-compose.yml
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']
  #       labels:
  #         service: 'mysql'

  # NGINX Exporter (optional - requires nginx-prometheus-exporter)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']
  #       labels:
  #         service: 'nginx'

  # Node Exporter for system metrics (optional)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         service: 'host-metrics'
